### ISSUE TITLE
Doesn't work in IE11

### ISSUE THREAD

**Issue by AndrewBogushevich** [DmitrySkyrat/repair-design-project#5]
Not sure are we going to support IE. IF you don't bother about it feel free to close issue.
https://github.com/DmitrySkyrat/repair-design-project/blob/b0a202df1d7eee6f0dd318a690c5c8d084daf96b/src/style/app.scss#L114

**Comment by DmitrySkyrat** [comment]
Browser Support: Google Chrome, Mozilla Firefox. Optional: Microsoft Edge / Safari.
