### ISSUE TITLE
What is the reason to add this block? seem like you can add padding directly to `.main-part__turnkey-approvement`

### ISSUE THREAD

**Issue by AndrewBogushevich** [DmitrySkyrat/repair-design-project#7]
https://github.com/DmitrySkyrat/repair-design-project/blob/b0a202df1d7eee6f0dd318a690c5c8d084daf96b/src/public/index.html#L40

**Comment by DmitrySkyrat** [comment]
Deleted forewer from index.htm, close the issue, please
